### ISSUE TITLE
error while launching app

### ISSUE THREAD

**Issue by jeremygachet** [mayorainfotech/facebook-clone-ionic-and-firebase#2]
I just bought and install the app. 
When I launch it, just after user signin (which work well) I got this issue, blocking everything.

```
Error: Uncaught (in promise): false
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at c (http://localhost:8100/build/polyfills.js:3:19461)
    at http://localhost:8100/build/polyfills.js:3:20233
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4499:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)
    at o (http://localhost:8100/build/polyfills.js:3:7894)
    at e.invokeTask [as invoke] (http://localhost:8100/build/polyfills.js:3:16823)
    at p (http://localhost:8100/build/polyfills.js:2:27648)
```

Could you please help me ?

**Comment by jeremygachet** [comment]
It was just an issue with my npm installation. sorry for that
